# Formatting style
max_width = 100
use_small_heuristics = "Max"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Struct and function formatting
brace_style = "SameLineWhere"
fn_single_line = true
empty_item_single_line = true
struct_lit_single_line = false
struct_lit_width = 40
struct_variant_width = 40

# Import formatting
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Misc
format_code_in_doc_comments = true
normalize_doc_attributes = true
edition = "2021"
